# Site settings
title: Quilombo Driven Development
email: your-email@domain.com
description: "Un poquito de Javascript sin romper nada" 
baseurl: ""
url: "https://quilombodd.herokuapp.com/"
twitter_username: alancampora
github_username:  alancampora

# Build settings
markdown: kramdown
permalink: pretty
gems: ['kramdown']
exclude: ['config.ru', 'Gemfile', 'Gemfile.lock', 'vendor', 'Procfile', 'Rakefile']

source: ./
destination: ./dist/
