exclude:  [ Gemfile, Gemfile.lock, Procfile, vendor]
sass:
  style: compressed
defaults:
    -
     scope:
         path: ""
     values:
         lang: es
         base-url: "/"
         pages-url: "pages"
    -
     scope:
         path: en
     values:
         lang: en
         base-url: "/en/"
         pages-url: "pages"
            
             
translate:
    home: 
        en: "Home"
        es: "Inicio"
    about:
        en: "About"
        es: "Acerca"
