exclude:  [ Gemfile, Gemfile.lock, Procfile, vendor]
sass:
  style: compressed
highlighter: rouge
google_analytics: "UA-98650718-1" 
defaults:
    -
     scope:
         path: ""
     values:
         lang: es
         base-url: "/"
         pages-url: "pages"
    -
     scope:
         path: en
     values:
         lang: en
         base-url: "/en/"
         pages-url: "pages"
            
             
translate:
    home: 
        en: "Home"
        es: "Inicio"
    about:
        en: "About"
        es: "Acerca"
    glosarry:
        en: "Glosarry"
        es: "Glosario"
    comments:
        en: "Comments"
        es: "Comentarios"
    commentInput: 
        en: "New comment" 
        es: "Comentario nuevo"
    commentInputNamePh: 
        en: "Name" 
        es: "Nombre"
    commentInputEmailPh: 
        en: "morty@domain.com" 
        es: "morty@dominio.com"
    commentInputMessagePh: 
        en: "Comment" 
        es: "Comentario"
    send: 
        en: "Send" 
        es: "Enviar" 


